### ISSUE TITLE
Create about us 

### ISSUE THREAD

**Issue by NavpreetDevpuri** [TrashMate/TrashMate#4]
Copy contact.html
Just change `center-div` 
https://github.com/TrashMate/TrashMate/blob/db044c01889eceaf97bdff8ecd9997a385803044/contact.html#L137
create `contact.css` or if you want to use scss than create `_contact.scss` to handle styles

**Comment by Maskgirl** [comment]
i have to change contact div class to contact-div?

**Comment by NavpreetDevpuri** [comment]
no need to change class names.
